export default const constants = {
	ADD_CLIENT: "ADD_CLIENT"
	REMOVE_CLIENT: "REMOVE_CLIENT"
	SEARCH_CLIENTS: "SEARCH_CLIENTS"
	CANCEL_SEARCH: "CANCEL_SEARCH"
	CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS"
	CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS"
	ADD_CLIENT_PROPERTY: "ADD_CLIENT_PROPERTY"
	EDIT_CLIENT_PROPERTY: "EDIT_CLIENT_PROPERTY"
	REMOVE_CLIENT_PROPERTY: "REMOVE_CLIENT_PROPERTY"
	ADD_ERROR: "ADD_ERROR"
	CLEAR_ERROR: "CLEAR_ERROR"
}