const constants = {
	USER_LOGIN: "USER_LOGIN",

	SHOW_SIDEBAR: "SHOW_SIDEBAR",
	HIDE_SIDEBAR: "HIDE_SIDEBAR",
	TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",

	ACTIVE_CLIENT: "ACTIVE_CLIENT",

	ADD_CLIENT: "ADD_CLIENT",
	REMOVE_CLIENT: "REMOVE_CLIENT",

	SEARCH_CLIENTS: "SEARCH_CLIENTS",
	CANCEL_SEARCH: "CANCEL_SEARCH",
	CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
	CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",

	EDIT_NAME: "EDIT_NAME",
	EDIT_SLUG: "EDIT_SLUG",

	ADD_CLIENT_PROPERTY: "ADD_CLIENT_PROPERTY",
	EDIT_CLIENT_PROPERTY: "EDIT_CLIENT_PROPERTY",
	REMOVE_CLIENT_PROPERTY: "REMOVE_CLIENT_PROPERTY",

	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR"
}

export default constants